name: Eslint

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run eslint
        run: rm -rf package-lock.json && npm cache clean --force && npm cache verify && npm i && ./node_modules/eslint/bin/eslint.js --fix .
