name: reviewdog
on: 
  pull_request:
    branches:
      - 'main'
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            eslint_flags: '**/*.{ts,tsx}'

          
          